name: MEISTER
channels:
  - conda-forge

dependencies:
  - h5py
  - hdf5
  - pandas
  - python=3.8
  - yaml
  - matplotlib
  - seaborn
  - pip
  - scipy
  - scikit-learn
  - tqdm
  - numpy==1.24.3
  - requests
  - ipywidgets
  - scikit-image
  - opencv
  - imagecodecs
  #- tensorflow
  - pip:
    - spike-py
    - argparse
    - pyimzml
    - pyMSpec
    - tables
    - xgboost
    - shap
    - brain-isotopic-distribution
